package brotherjing.com.leomainjector;

/**
 * Created by jingyanga on 2016/9/5.
 */
public class LeomaInjector {

    public static void inject(Object host){
        String hostName = host.getClass().getName();
        try{

            Class<?> clazz = Class.forName(hostName+"$$InnerInjector");//this class does not exist until compiling.
            InnerInjector innerInjector = (InnerInjector)clazz.newInstance();
            innerInjector.inject(host);//this method is generated by annotation compiler, but can be called in code.
        }catch (Exception e){
            e.printStackTrace();
        }
    }

}
